services:
  backend:
    build:
      context: .                #  <- repo root (important!)
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"

  frontend:
    build:
      context: .                #  root as well
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
