services:
  - name: backend
    type: web
    env: docker
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    plan: free
    autoDeploy: true
    buildCommand: ""
    envVars:
      - key: PORT
        value: 5000

  - name: frontend
    type: web
    env: docker
    dockerfilePath: frontend/Dockerfile
    dockerContext: frontend
    plan: free
    autoDeploy: true
    buildCommand: ""
    envVars:
      - key: PORT
        value: 80
