services:
  - name: backend
    type: web
    env: docker
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    plan: free
    autoDeploy: true
    buildCommand: ""
    startCommand: gunicorn app:app --bind 0.0.0.0:5000
    envVars:
      - key: PORT
        value: 5000

  - name: frontend
    type: web
    env: docker
    dockerfilePath: frontend/Dockerfile
    dockerContext: frontend
    plan: free
    autoDeploy: true
    buildCommand: ""
    startCommand: serve -s build -l 80
    envVars:
      - key: PORT
        value: 80
