name: Build & Push Docker Images

on:
  push:
    branches: [ main ]   # change branch if needed

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_BACKEND: ${{ secrets.REGISTRY_USER }}/crop-backend
      IMAGE_FRONTEND: ${{ secrets.REGISTRY_USER }}/crop-frontend
      TAG: ${{ github.sha }}

    steps:
    - uses: actions/checkout@v3

    # ---- Set up Docker Buildx ----
    - uses: docker/setup-buildx-action@v2

    # ---- Log in to Docker Hub (or your registry) ----
    - name: Login to registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASS }}

    # ---- Build & push backend ----
    - name: Build & push backend image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: backend/Dockerfile
        push: true
        tags: |
          ${{ env.IMAGE_BACKEND }}:latest
          ${{ env.IMAGE_BACKEND }}:${{ env.TAG }}

    # ---- Build & push frontend ----
    - name: Build & push frontend image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: frontend/Dockerfile
        push: true
        tags: |
          ${{ env.IMAGE_FRONTEND }}:latest
          ${{ env.IMAGE_FRONTEND }}:${{ env.TAG }}
